// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozx6ocqkv5n4XdwEQ7IGMIYzIJ9g9_8g',
    appId: '1:116412658576:web:c6eb901e7ed1554e5fb915',
    messagingSenderId: '116412658576',
    projectId: 'edusync-firebase-915d5',
    authDomain: 'edusync-firebase-915d5.firebaseapp.com',
    storageBucket: 'edusync-firebase-915d5.firebasestorage.app',
    measurementId: 'G-Z6TSJ8QC9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtYeAJyAQAcSjFEW8g53EUKFuDa3o-qyk',
    appId: '1:116412658576:android:42fb0936f4ff14525fb915',
    messagingSenderId: '116412658576',
    projectId: 'edusync-firebase-915d5',
    storageBucket: 'edusync-firebase-915d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwfkLjrOfBMBt6Jj8nseUkVVJOao34CE',
    appId: '1:116412658576:ios:b672bc3bf39f785f5fb915',
    messagingSenderId: '116412658576',
    projectId: 'edusync-firebase-915d5',
    storageBucket: 'edusync-firebase-915d5.firebasestorage.app',
    iosBundleId: 'com.example.kelompok3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTwfkLjrOfBMBt6Jj8nseUkVVJOao34CE',
    appId: '1:116412658576:ios:b672bc3bf39f785f5fb915',
    messagingSenderId: '116412658576',
    projectId: 'edusync-firebase-915d5',
    storageBucket: 'edusync-firebase-915d5.firebasestorage.app',
    iosBundleId: 'com.example.kelompok3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAozx6ocqkv5n4XdwEQ7IGMIYzIJ9g9_8g',
    appId: '1:116412658576:web:7dd2ea6f59fba19a5fb915',
    messagingSenderId: '116412658576',
    projectId: 'edusync-firebase-915d5',
    authDomain: 'edusync-firebase-915d5.firebaseapp.com',
    storageBucket: 'edusync-firebase-915d5.firebasestorage.app',
    measurementId: 'G-XBB4Z7S4NV',
  );

}